# coding: utf-8

"""
    PocketSmith

    The public PocketSmith API  # noqa: E501

    The version of the OpenAPI document: 2.0
    Contact: api@pocketsmith.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from pocketsmith.configuration import Configuration


class CategoryRule(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'category': 'Category',
        'created_at': 'datetime',
        'id': 'int',
        'payee_matches': 'str',
        'updated_at': 'datetime'
    }

    attribute_map = {
        'category': 'category',
        'created_at': 'created_at',
        'id': 'id',
        'payee_matches': 'payee_matches',
        'updated_at': 'updated_at'
    }

    def __init__(self, category=None, created_at=None, id=None, payee_matches=None, updated_at=None, local_vars_configuration=None):  # noqa: E501
        """CategoryRule - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._category = None
        self._created_at = None
        self._id = None
        self._payee_matches = None
        self._updated_at = None
        self.discriminator = None

        if category is not None:
            self.category = category
        if created_at is not None:
            self.created_at = created_at
        if id is not None:
            self.id = id
        if payee_matches is not None:
            self.payee_matches = payee_matches
        if updated_at is not None:
            self.updated_at = updated_at

    @property
    def category(self):
        """Gets the category of this CategoryRule.  # noqa: E501


        :return: The category of this CategoryRule.  # noqa: E501
        :rtype: Category
        """
        return self._category

    @category.setter
    def category(self, category):
        """Sets the category of this CategoryRule.


        :param category: The category of this CategoryRule.  # noqa: E501
        :type: Category
        """

        self._category = category

    @property
    def created_at(self):
        """Gets the created_at of this CategoryRule.  # noqa: E501

        When the category rule was created.  # noqa: E501

        :return: The created_at of this CategoryRule.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this CategoryRule.

        When the category rule was created.  # noqa: E501

        :param created_at: The created_at of this CategoryRule.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def id(self):
        """Gets the id of this CategoryRule.  # noqa: E501

        The unique identifier of the category rule.  # noqa: E501

        :return: The id of this CategoryRule.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this CategoryRule.

        The unique identifier of the category rule.  # noqa: E501

        :param id: The id of this CategoryRule.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def payee_matches(self):
        """Gets the payee_matches of this CategoryRule.  # noqa: E501

        The keyword/s to match the transactions payees.  # noqa: E501

        :return: The payee_matches of this CategoryRule.  # noqa: E501
        :rtype: str
        """
        return self._payee_matches

    @payee_matches.setter
    def payee_matches(self, payee_matches):
        """Sets the payee_matches of this CategoryRule.

        The keyword/s to match the transactions payees.  # noqa: E501

        :param payee_matches: The payee_matches of this CategoryRule.  # noqa: E501
        :type: str
        """

        self._payee_matches = payee_matches

    @property
    def updated_at(self):
        """Gets the updated_at of this CategoryRule.  # noqa: E501

        When the category rule was last updated.  # noqa: E501

        :return: The updated_at of this CategoryRule.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this CategoryRule.

        When the category rule was last updated.  # noqa: E501

        :param updated_at: The updated_at of this CategoryRule.  # noqa: E501
        :type: datetime
        """

        self._updated_at = updated_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CategoryRule):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CategoryRule):
            return True

        return self.to_dict() != other.to_dict()
