# coding: utf-8

"""
    PocketSmith

    The public PocketSmith API  # noqa: E501

    The version of the OpenAPI document: 2.0
    Contact: api@pocketsmith.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from pocketsmith.configuration import Configuration


class InlineObject11(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'file_data': 'str',
        'file_name': 'str',
        'title': 'str'
    }

    attribute_map = {
        'file_data': 'file_data',
        'file_name': 'file_name',
        'title': 'title'
    }

    def __init__(self, file_data=None, file_name=None, title=None, local_vars_configuration=None):  # noqa: E501
        """InlineObject11 - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._file_data = None
        self._file_name = None
        self._title = None
        self.discriminator = None

        if file_data is not None:
            self.file_data = file_data
        if file_name is not None:
            self.file_name = file_name
        if title is not None:
            self.title = title

    @property
    def file_data(self):
        """Gets the file_data of this InlineObject11.  # noqa: E501

        The base64-encoded contents of the source file. The supported file types are png, jpg, pdf, xls, xlsx, doc, docx.  # noqa: E501

        :return: The file_data of this InlineObject11.  # noqa: E501
        :rtype: str
        """
        return self._file_data

    @file_data.setter
    def file_data(self, file_data):
        """Sets the file_data of this InlineObject11.

        The base64-encoded contents of the source file. The supported file types are png, jpg, pdf, xls, xlsx, doc, docx.  # noqa: E501

        :param file_data: The file_data of this InlineObject11.  # noqa: E501
        :type: str
        """

        self._file_data = file_data

    @property
    def file_name(self):
        """Gets the file_name of this InlineObject11.  # noqa: E501

        The file name of the attachment.  # noqa: E501

        :return: The file_name of this InlineObject11.  # noqa: E501
        :rtype: str
        """
        return self._file_name

    @file_name.setter
    def file_name(self, file_name):
        """Sets the file_name of this InlineObject11.

        The file name of the attachment.  # noqa: E501

        :param file_name: The file_name of this InlineObject11.  # noqa: E501
        :type: str
        """

        self._file_name = file_name

    @property
    def title(self):
        """Gets the title of this InlineObject11.  # noqa: E501

        The title of the attachment. If the title is blank or not provided, the title will derived from the file name.  # noqa: E501

        :return: The title of this InlineObject11.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this InlineObject11.

        The title of the attachment. If the title is blank or not provided, the title will derived from the file name.  # noqa: E501

        :param title: The title of this InlineObject11.  # noqa: E501
        :type: str
        """

        self._title = title

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineObject11):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineObject11):
            return True

        return self.to_dict() != other.to_dict()
